export const inspectionTabs = [
// {
//     key: "History",
//     label: "History",
//      subIssues: [
//       { key: "vinInspection", label: "VIN Inspection" },
//       { key: "serviceRecalls", label: "Service Recalls Performed" },
//       { key: "vehicleHistory", label: "Vehicle History Obtained" }, 
//       { key: "scheduledMaintenance", label: "Scheduled Maintenance Performed" },
//      ],
// },
  {
    key: "chassis",
    label: "Chassis",
    classification: ["Chassis inspection","Paint and chassis inspection"],
    subIssues: [
      { key: "chassisCondition", label: "Chassis condition" }
    ]
  },
  {
    key: "paint",
    label: "Paint",
    classification: ["Paint inspection","Paint and chassis inspection"],
    subIssues: [
      { key: "paintCondition", label: "Paint condition" }
    ]
  },
  {
    key: "obd",
    label: "OBD",
    classification: ["OBD inspection"],
    subIssues: [
      { key: "obdCondition", label: "OBD" }
    ]
  },
 {
    key: "exterior",
    label: "Exterior",
    classification: ["360 inspection"],
    subIssues: [
      { key: "bodyPanelInspection", label: "Body Panel Inspection" },
      { key: "bumperFasciaInspection", label: "Bumper, Fascia Inspection" },
      { key: "hoodBootTailgateRoof", label: "Hood, Boot (Trunk), Tailgate & Roof" },
      { key: "doorsInspection", label: "Doors Inspection" },
      { key: "releaseMechanisms", label: "Automatic/Manual Release Mechanisms, Hinges, Prop Rod/Gas Struts Operate Properly" },
      { key: "powerLiftGate", label: "Power Lift Gate, Power-Sliding Door Operation" },
      { key: "grilleTrimRoofRack", label: "Grille, Trim and Roof Rack Inspection" },
      { key: "deployableRunningBoards", label: "Deployable, Running Boards" },
      { key: "windowGlassInspection", label: "Windshield, Side and Rear-Window Glass Inspection" },
      { key: "outsideMirrorInspection", label: "Outside Mirror Inspection" },
      { key: "frontEndLights", label: "Front-End Exterior Lights" },
      { key: "backEndLights", label: "Back-End Exterior Lights" },
      { key: "sideExteriorLights", label: "Side Exterior Lights" },
      { key: "autoOnOffLighting", label: "Auto On & Off Lighting" },
      { key: "lights", label: "Lights" },
      { key: "paintCheck", label: "Paint Check" },
      { key: "fendersInspection", label: "Fenders Inspection" },
      { key: "hazardLights", label: "Hazard Lights" },
    ],
  },
{
    key: "interior",
    label: "Interior",
    classification: ["360 inspection"],
    subIssues: [
      { key: "airbags", label: "Airbags" },
      { key: "safetyBelts", label: "Safety belts" },
      { key: "radioCassetteCDSpeakers", label: "Radio, Cassette, CD and Speakers" },
      { key: "navigationSystem", label: "Navigation System" },
      { key: "heatingSystem", label: "Heating System" },
      { key: "defogDefrost", label: "Defog/Defrost" },
      { key: "tiltTelescopicSteeringWheel", label: "Tilt/Telescopic Steering Wheel" },
      { key: "steeringColumnLock", label: "Steering Column Lock" },
      { key: "steeringWheelControls", label: "Steering Wheel Controls" },
      { key: "instrumentPanelWarningLights", label: "Instrument Panel and Warning Lights" },
      { key: "washers", label: "Washers" },
      { key: "interiorLights", label: "Interior Courtesy, Dome and Map Lights" },
      { key: "manualOutsideMirrors", label: "Manual outside Rearview Mirrors" },
      { key: "powerOutsideMirrors", label: "Power outside Rearview Mirrors and Auto-Dimming Rearview Mirror" },
      { key: "rearViewCamera", label: "Rear View Camera" },
      { key: "activeParkAssist", label: "Active Park Assist" },
      { key: "powerOutletsLighter", label: "Power Outlets and Lighter" },
      { key: "ashtrays", label: "Ashtrays" },
      { key: "gloveBoxConsole", label: "Glove Box and Center Armrest/Console" },
      { key: "sunVisorsVanityMirror", label: "Sun Visors, Vanity Mirror and Light" },
      { key: "adjustablePedals", label: "Adjustable pedals (if equipped)" },
      { key: "interiorOdorFree", label: "Interior Odor-Free" },
      { key: "carpet", label: "Carpet" },
      { key: "doorTrimPanels", label: "Door Trim and Door Panels" },
      { key: "headliner", label: "Headliner" },
      { key: "seatUpholstery", label: "Seat Upholstery" },
      { key: "seatAdjustment", label: "Seat and Head Restraint Adjustment" },
      { key: "foldingSeats", label: "Folding Seats" },
      { key: "sunroof", label: "Sunroof" },
      { key: "moonRoof", label: "Moon roof" },
      { key: "doorHandlesRelease", label: "Door Handles and Release Mechanisms" },
      { key: "remoteEntryPushStart", label: "Remote Entry System and Push-Button Start System" },
      { key: "doorLocks", label: "Door Locks" },
      { key: "childSafetyLocks", label: "Child Safety Locks" },
      { key: "windowControls", label: "Window Controls" },
      { key: "remoteDecklidFuelRelease", label: "Remote Decklid and Fuel Filler Door Release" },
      { key: "luggageCompartmentLight", label: "Luggage Compartment and Cargo Area Light" },
      { key: "vehicleJackToolKit", label: "Vehicle Jack and Tool Kit" },
      { key: "spareTireSizeType", label: "Spare Tire Size, Type and Sidewall Inspection" },
      { key: "spareTireTreadPressure", label: "Spare Tire Tread Depth, Air Pressure Inspection" },
      { key: "emergencyTrunkRelease", label: "Emergency Trunk-Lid Release" },
      { key: "absWarningLight", label: "ABS Warning Light" },
      { key: "tirePressureMonitoringLight", label: "Tire Pressure Monitoring System Light" },
      { key: "convertibleTop", label: "Convertible Top" },
      { key: "heatedSeats", label: "Heated Seats" },
      { key: "floorMats", label: "Floor Mats" },
      { key: "wipers", label: "Wipers" },
      { key: "horn", label: "Horn" },
      { key: "acCompressor", label: "Air conditioning Compressor" },
    ],
  },
  {
    key: "underhood",
    label: "Under Hood",
    classification: ["360 inspection"],
    subIssues: [
      { key: "automaticTransaxleTransmission", label: "Automatic Transaxle/Transmission" },
      { key: "transferCase", label: "Transfer Case" },
      { key: "driveAxle", label: "Drive Axle" },
      { key: "washerFluid", label: "Washer Fluid" },
      { key: "acSystemCharge", label: "Air Conditioning System Charge" },
      { key: "hosesLinesFittings", label: "Hoses, Lines and Fittings" },
      { key: "belts", label: "Belts" },
      { key: "wiring", label: "Wiring" },
      { key: "oilInAirCleanerHousing", label: "Oil in Air Cleaner Housing" },
      { key: "coolantInOil", label: "Water, Sludge or Engine Coolant in Oil" },
      { key: "engineMounts", label: "Engine Mounts" },
      { key: "turbochargerCooler", label: "Inspect Turbocharger Cooler" },
      { key: "coolingFans", label: "Cooling Fans, Clutches and Motor" },
      { key: "coolantRecoveryTank", label: "Coolant Recover Tank" },
      { key: "fuelPumpNoise", label: "Fuel Pump Noise Normal" },
      { key: "starterOperation", label: "Starter Operation" },
      { key: "alternatorOutput", label: "Alternator Output" },
      { key: "battery", label: "Battery" },
      { key: "ignitionSystem", label: "Ignition System" },
      { key: "engineAirFilter", label: "Engine Air Filter" },
      { key: "fuelFilter", label: "Fuel Filter" },
      { key: "cabinAirFilter", label: "Cabin Air Filter" },
      { key: "radiator", label: "Radiator" },
      { key: "fluidLeaks", label: "Fluid Leaks" },
      { key: "powerSteeringFluid", label: "Power Steering Fluid" },
      { key: "coolant", label: "Coolant" },
      { key: "brakeFluid", label: "Brake Fluid" },
      { key: "engineOrGearOilLeak", label: "Engine or Gear Oil Leak" },
    ],
  },
  {
  key: "underChassis",
  label: "Under Chassis Inspection",
  classification: ["360 inspection"],
  subIssues: [
    { key: "chassisCondition", label: "Chassis Condition" },
    { key: "fuelSupplySystem", label: "Fuel Supply System" },
    { key: "exhaustSystemCondition", label: "Exhaust System Condition" },
    { key: "emissionsControlTest", label: "Emissions Control Test" },
    { key: "automaticTransmissionTransaxle", label: "Automatic Transmission, Transaxle" },
    { key: "manualTransmissionDifferentialTransferCase", label: "Manual Transmission/Transaxle, Differential and Transfer Case" },
    { key: "fourByFourHubOperation", label: "4x4 Hub Operation" },
    { key: "universalJointsCVJointsBoots", label: "Universal Joints, CV Joints and CV Joint Boots" },
    { key: "transmissionMounts", label: "Transmission Mounts (not cracked, broken or oil soaked)" },
    { key: "differentialDriveAxle", label: "Differential, Drive Axle" },
    { key: "tiresWheelsMatch", label: "Tires and Wheels Match and Are Correct Size" },
    { key: "tireTreadDepth", label: "Tire Tread Depth" },
    { key: "tireCondition", label: "Tires Condition" },
    { key: "wheelCoversCaps", label: "Wheel Covers and Center Caps" },
    { key: "rackPinionLinkageBoots", label: "Rack-and-Pinion, Linkage and Boots" },
    { key: "controlArmsBushingsJoints", label: "Control Arms, Bushings and Ball Joints" },
    { key: "tieRodsIdlerArm", label: "Tie-Rods and Idler Arm" },
    { key: "swayBarsLinksBushings", label: "Sway Bars, Links and Bushings" },
    { key: "strutsShocks", label: "Struts and Shock" },
    { key: "wheelAlignment", label: "Wheel Alignment (check if necessary)" },
    { key: "floorInspection", label: "Floor Inspection" },
    { key: "frameCrossMembersBulkhead", label: "Frame and Cross Members & Bulkhead" },
    { key: "antenna", label: "Antenna" },
    { key: "powerSteeringPump", label: "Power Steering Pump" },
    { key: "springs", label: "Springs" },
    { key: "wheels", label: "Wheels" },
    { key: "tirePressure", label: "Tire Pressure" }
  ]
},
 {
  key: "brakes",
  label: "Brake",
  classification: ["360 inspection"],
  subIssues: [
    { key: "calipersWheelCylinders", label: "Calipers and Wheel Cylinders" },
    { key: "brakePadsShoes", label: "Brake Pads and Shoes" },
    { key: "rotorsDrums", label: "Rotors and Drums" },
    { key: "brakeLinesHosesFittings", label: "Brake Lines, Hoses and Fittings" },
    { key: "masterCylinderBooster", label: "Master Cylinder and Booster" },
    { key: "parkingBrake", label: "Parking Brake" },
  ],
},
  {
    key: "diagnostics",
    label: "Diagnostics",
    classification: ["360 inspection"],
    subIssues: [
      { key: "obdCheck", label: "On Board Diagnostics Check (OBD)" },
    ],
  },
  // {
  //   key: "convenience",
  //   label: "Convenience",
  //   subIssues: [
  //     { key: "ownersGuide", label: "Owner’s Guide" },
  //     { key: "keysRemotes", label: "Keys and Remote Controls" },
  //     { key: "universalTransmitter", label: "Universal Transmitter (Garage Door Opener)" },
  //     { key: "fullFuelLevel", label: "Full Fuel Level" },
  //   ],
  // },
  {
  key: "roadTest",
  label: "Road Test",
  classification: ["360 inspection"],
  subIssues: [
    { key: "engineStartsIdles", label: "Engine Starts and Idles Operation" },
    { key: "remoteStartsSystem", label: "Remote Starts System Operation" },
    { key: "engineAcceleratesCruises", label: "Engine Accelerates and Cruises Properly & Smoothly" },
    { key: "engineNoiseNormal", label: "Engine Noise Normal (Cold/Hot & High/Low Speeds)" },
    { key: "transmissionShiftQuality", label: "Auto/Manual Transmission/Transaxle Operation – Cold and Hot Shift Quality" },
    { key: "transmissionNoiseNormal", label: "Auto/Manual Transmission/Transaxle Noise Normal – Cold and Hot" },
    { key: "shiftInterlockOperates", label: "Shift Interlock Operates Properly" },
    { key: "driveAxleTransferCaseNoise", label: "Drive Axle/Transfer Case Operation Noise Normal" },
    { key: "clutchOperates", label: "Clutch Operates Properly" },
    { key: "steersNormally", label: "Steers Normally (Response, Centering)" },
    { key: "bodySuspensionSqueaksRattles", label: "Body and Suspension Squeaks and Rattles" },
    { key: "strutsShocksOperate", label: "Struts/Shocks Operate Properly" },
    { key: "brakesAbsOperate", label: "Brakes/ABS Operate Properly" },
    { key: "gaugesOperate", label: "Gauges Operate Properly" },
    { key: "driverSelectMemorySystems", label: "Driver Select/Memory Profile Systems" },
    { key: "noAbnormalWindNoise", label: "No Abnormal Wind Noise" },
    { key: "cruiseControl", label: "Cruise Control" },
    { key: "others", label: "Others" }
  ]
},

{
  key: "exterior",
  label: "Exterior",
  classification: ["Auction Comprehensive Inspection"],
  subIssues: [
    { key: "bodyPanelInspection", label: "Body Panel Inspection" },
    { key: "bumperFasciaInspection", label: "Bumper, Fascia Inspection" },
    { key: "hoodBootTailgateRoof", label: "Hood, Boot (Trunk), Tailgate & Roof" },
    { key: "doorsInspection", label: "Doors Inspection" },
    { key: "powerLiftGate", label: "Power Lift Gate, Power-Sliding Door Operation" },
    { key: "grilleTrimRoofRack", label: "Grille, Trim and Roof Rack Inspection" },
    { key: "windowGlassInspection", label: "Windshield, Side and Rear-Window Glass Inspection" },
    { key: "outsideMirrorInspection", label: "Outside Mirror Inspection" },
    { key: "paintCheck", label: "Paint Check" }
  ],
},
{
  key: "interior",
  label: "Interior",
  classification: ["Auction Comprehensive Inspection"],
  subIssues: [
    { key: "airbags", label: "Airbags" },
    { key: "safetyBelts", label: "Safety belts" },
    { key: "washers", label: "Washers" },
    { key: "manualOutsideMirrors", label: "Manual outside Rearview Mirrors" },
    { key: "rearViewCamera", label: "Rear View Camera" },
    { key: "activeParkAssist", label: "Active Park Assist" },
    { key: "sunVisorsVanityMirror", label: "Sun Visors, Vanity Mirror and Light" },
    { key: "interiorOdorFree", label: "Interior Odor-Free" },
    { key: "carpet", label: "Carpet" },
    { key: "doorTrimPanels", label: "Door Trim and Door Panels" },
    { key: "seatAdjustment", label: "Seat and Head Restraint Adjustment" },
    { key: "foldingSeats", label: "Folding Seats" },
    { key: "doorLocks", label: "Door Locks" },
    { key: "windowControls", label: "Window Controls" },
    { key: "absWarningLight", label: "ABS Warning Light" },
    { key: "tirePressureMonitoringLight", label: "Tire Pressure Monitoring System Light" },
    { key: "wipers", label: "Wipers" },
    { key: "horn", label: "Horn" },
    { key: "acCompressor", label: "Air conditioning Compressor" },
  ],
},
{
  key: "underhood",
  label: "Under Hood",
  classification: ["Auction Comprehensive Inspection"],
  subIssues: [
    { key: "transferCase", label: "Transfer Case" },
    { key: "driveAxle", label: "Drive Axle" },
    { key: "acSystemCharge", label: "Air Conditioning System Charge" },
    { key: "coolantInOil", label: "Water, Sludge or Engine Coolant in Oil" },
    { key: "engineMounts", label: "Engine Mounts" },
    { key: "coolantRecoveryTank", label: "Coolant Recover Tank" },
    { key: "starterOperation", label: "Starter Operation" },
    { key: "radiator", label: "Radiator" },
    { key: "fluidLeaks", label: "Fluid Leaks" },
    { key: "powerSteeringFluid", label: "Power Steering Fluid" },
    { key: "coolant", label: "Coolant" },
    { key: "brakeFluid", label: "Brake Fluid" },
    { key: "engineOrGearOilLeak", label: "Engine or Gear Oil Leak" },
  ],
},
{
key: "underChassis",
label: "Under Chassis Inspection",
classification: ["Auction Comprehensive Inspection"],
subIssues: [
  { key: "chassisCondition", label: "Chassis Condition" },
  { key: "exhaustSystemCondition", label: "Exhaust System Condition" },
  { key: "emissionsControlTest", label: "Emissions Control Test" },
  { key: "automaticTransmissionTransaxle", label: "Automatic Transmission, Transaxle" },
  { key: "fourByFourHubOperation", label: "4x4 Hub Operation" },
  { key: "universalJointsCVJointsBoots", label: "Universal Joints, CV Joints and CV Joint Boots" },
  { key: "transmissionMounts", label: "Transmission Mounts (not cracked, broken or oil soaked)" },
  { key: "differentialDriveAxle", label: "Differential, Drive Axle" },
  { key: "tireCondition", label: "Tires Condition" },
  { key: "tieRodsIdlerArm", label: "Tie-Rods and Idler Arm" },
  { key: "strutsShocks", label: "Struts and Shock" },
  { key: "wheelAlignment", label: "Wheel Alignment (check if necessary)" },
  { key: "floorInspection", label: "Floor Inspection" },
  { key: "frameCrossMembersBulkhead", label: "Frame and Cross Members & Bulkhead" },
  { key: "wheels", label: "Wheels" },
  { key: "tirePressure", label: "Tire Pressure" }
]
},
{
key: "brakes",
label: "Brake",
classification: ["Auction Comprehensive Inspection"],
subIssues: [
  { key: "brakePadsShoes", label: "Brake Pads and Shoes" },
  { key: "parkingBrake", label: "Parking Brake" },
],
},
{
  key: "diagnostics",
  label: "Diagnostics",
  classification: ["Auction Comprehensive Inspection"],
  subIssues: [
    { key: "obdCheck", label: "On Board Diagnostics Check (OBD)" },
  ],
},
{
key: "roadTest",
label: "Road Test",
classification: ["Auction Comprehensive Inspection"],
subIssues: [
  { key: "engineStartsIdles", label: "Engine Starts and Idles Operation" },
  { key: "engineAcceleratesCruises", label: "Engine Accelerates and Cruises Properly & Smoothly" },
  { key: "engineNoiseNormal", label: "Engine Noise Normal (Cold/Hot & High/Low Speeds)" },
  { key: "transmissionShiftQuality", label: "Auto/Manual Transmission/Transaxle Operation – Cold and Hot Shift Quality" },
  { key: "transmissionNoiseNormal", label: "Auto/Manual Transmission/Transaxle Noise Normal – Cold and Hot" },
  { key: "shiftInterlockOperates", label: "Shift Interlock Operates Properly" },
  { key: "strutsShocksOperate", label: "Struts/Shocks Operate Properly" },
  { key: "brakesAbsOperate", label: "Brakes/ABS Operate Properly" },
  { key: "gaugesOperate", label: "Gauges Operate Properly" },
  { key: "driverSelectMemorySystems", label: "Driver Select/Memory Profile Systems" },
  { key: "noAbnormalWindNoise", label: "No Abnormal Wind Noise" },
  { key: "cruiseControl", label: "Cruise Control" },
  { key: "others", label: "Others" }
]
}

];
